{
    'name': 'Charge ERP Core',
    'version': '1.0',
    'summary': 'Core module for Charge ERP',
    'description': """
        This is the core module for the Charge ERP system.
    """,
    'author': 'Charge',
    'website': 'https://www.charge-erp.com',
    'category': 'Education',
    'depends': ['base', 'mail', 'hr'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'wizard/attendee_wizard_views.xml',
        'views/session_views.xml',
        'views/student_views.xml',
        'views/course_views.xml',
        'views/course_enrollment_views.xml',
        'views/subject_views.xml',
        'views/book_issue_views.xml',
        'views/faculty_views.xml',
        'views/batch_views.xml',
        'views/program_level_views.xml',
        'views/program_views.xml',
        'views/department_views.xml',
        'views/category_views.xml',
        'views/academic_term_views.xml',
        'views/academic_year_views.xml',
        'views/tags_views.xml',
        'views/student_user_action.xml',
        'views/server_actions.xml',
        'views/menu_views.xml',
    ],
    'demo': [
        'demo/department_demo.xml',
        'demo/program_demo.xml',
        'demo/academic_year_demo.xml',
        'demo/subject_demo.xml',
        'demo/course_demo.xml',
        'demo/faculty_demo.xml',
        'demo/batch_demo.xml',
        'demo/student_demo.xml',
        'demo/course_enrollment_demo.xml',
    ],
    'installable': True,
    'application': True,
}